# -*- coding: utf-8 -*-
"""project_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaJNGacgHgq4qupGE1sUkFgdr5Yxhh-I
"""

import random


responses = {
      ('hello', 'hey', 'hi'): lambda: 'Hi there!',
      'how are you': lambda: 'I am fine, thank you!',
      'what is your name': lambda: 'My name is Chatbot.',
      'who are you' : lambda: 'I am a simple chatbot designed to answer your basic questions!',
      ('thanks', 'thank you'): lambda: 'You\'re welcome!',
      'what can you do': lambda: 'I can answer basic questions',
      ('generate a random number', 'generate another number') : lambda: f'here is your number: {random.randint(0, 100)}'
  }

def process(user_input, responses):

  # Logic to handle both string keys and tuple keys
  reply = "I am sorry, I do not understand that."
  for key, value in responses.items():
      if (isinstance(key, tuple) and user_input in key) or user_input == key:
              reply = value()
              break

  print(f"Chatbot: {reply}")

def rule_based_AI_chatbot():
    print("Chatbot started! Type 'quit' to exit.")
    while True:
      raw_input = input("You: ")
      user_input = raw_input.lower().strip()


      if user_input in ('quit', 'bye', 'exit', 'goodbye'):
          print("Chatbot: Goodbye! Have a great day!")
          break

      process(user_input, responses)




if __name__ == "__main__":
  rule_based_AI_chatbot()